// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Example

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArrayStructT struct {
	A float32 `json:"a"`
	B [15]int32 `json:"b"`
	C int8 `json:"c"`
	D [2]NestedStructT `json:"d"`
	E int32 `json:"e"`
	F [2]int64 `json:"f"`
}

func (t *ArrayStructT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	var d_a [2][2]int32
	for idx0 := 0; idx0 < 2; idx0++ {
		for idx1 := 0; idx1 < 2; idx1++ {
			d_a[idx0][idx1] = t.D[idx0].A[idx1]
		}
	}
	var d_b [2]TestEnum
	for idx0 := 0; idx0 < 2; idx0++ {
		d_b[idx0] = t.D[idx0].B
	}
	var d_c [2][2]TestEnum
	for idx0 := 0; idx0 < 2; idx0++ {
		for idx1 := 0; idx1 < 2; idx1++ {
			d_c[idx0][idx1] = t.D[idx0].C[idx1]
		}
	}
	var d_d [2][2]int64
	for idx0 := 0; idx0 < 2; idx0++ {
		for idx1 := 0; idx1 < 2; idx1++ {
			d_d[idx0][idx1] = t.D[idx0].D[idx1]
		}
	}
	return CreateArrayStruct(
		builder,
		t.A,
		t.B,
		t.C,
		d_a,
		d_b,
		d_c,
		d_d,
		t.E,
		t.F,
	)
}
func (rcv *ArrayStruct) UnPackTo(t *ArrayStructT) {
	t.A = rcv.A()
	for j := 0; j < 15; j++ {
		t.B[j] = rcv.B(j)
	}
	t.C = rcv.C()
	for j := 0; j < 2; j++ {
		x := NestedStruct{}
		t.D[j] = *rcv.D(&x, j).UnPack()
	}
	t.E = rcv.E()
	for j := 0; j < 2; j++ {
		t.F[j] = rcv.F(j)
	}
}

func (rcv *ArrayStruct) UnPack() *ArrayStructT {
	if rcv == nil {
		return nil
	}
	t := &ArrayStructT{}
	rcv.UnPackTo(t)
	return t
}

type ArrayStruct struct {
	_tab flatbuffers.Struct
}

func (rcv *ArrayStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArrayStruct) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ArrayStruct) A() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ArrayStruct) MutateA(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ArrayStruct) B(j int) int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4) + flatbuffers.UOffsetT(j*4))
}

func (rcv *ArrayStruct) BLength() int {
	return 15
}

func (rcv *ArrayStruct) MutateB(j int, n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4)+flatbuffers.UOffsetT(j*4), n)
}

func (rcv *ArrayStruct) C() int8 {
	return rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(64))
}
func (rcv *ArrayStruct) MutateC(n int8) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(64), n)
}

func (rcv *ArrayStruct) D(obj *NestedStruct, j int) *NestedStruct {
	if obj == nil {
		obj = new(NestedStruct)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+flatbuffers.UOffsetT(72)+flatbuffers.UOffsetT(j*32))
	return obj
}

func (rcv *ArrayStruct) DLength() int {
	return 2
}

func (rcv *ArrayStruct) E() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(136))
}
func (rcv *ArrayStruct) MutateE(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(136), n)
}

func (rcv *ArrayStruct) F(j int) int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(144) + flatbuffers.UOffsetT(j*8))
}

func (rcv *ArrayStruct) FLength() int {
	return 2
}

func (rcv *ArrayStruct) MutateF(j int, n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(144)+flatbuffers.UOffsetT(j*8), n)
}

func CreateArrayStruct(builder *flatbuffers.Builder, a float32, b [15]int32, c int8, d_a [2][2]int32, d_b [2]TestEnum, d_c [2][2]TestEnum, d_d [2][2]int64, e int32, f [2]int64) flatbuffers.UOffsetT {
	builder.Prep(8, 160)
	for idx0 := 2 - 1; idx0 >= 0; idx0-- {
		builder.PrependInt64(f[idx0])
	}
	builder.Pad(4)
	builder.PrependInt32(e)
	for idx0 := 2 - 1; idx0 >= 0; idx0-- {
		builder.Prep(8, 32)
		for idx1 := 2 - 1; idx1 >= 0; idx1-- {
			builder.PrependInt64(d_d[idx0][idx1])
		}
		builder.Pad(5)
		for idx1 := 2 - 1; idx1 >= 0; idx1-- {
			builder.PrependInt8(int8(d_c[idx0][idx1]))
		}
		builder.PrependInt8(int8(d_b[idx0]))
		for idx1 := 2 - 1; idx1 >= 0; idx1-- {
			builder.PrependInt32(d_a[idx0][idx1])
		}
	}
	builder.Pad(7)
	builder.PrependInt8(c)
	for idx0 := 15 - 1; idx0 >= 0; idx0-- {
		builder.PrependInt32(b[idx0])
	}
	builder.PrependFloat32(a)
	return builder.Offset()
}
