// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Example

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LargeArrayStructT struct {
	D [64]byte `json:"d"`
	E [64]float32 `json:"e"`
	F [64]bool `json:"f"`
	G [64]NestedStructT `json:"g"`
	H [64]TestEnum `json:"h"`
}

func (t *LargeArrayStructT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	var g_a [64][2]int32
	for idx0 := 0; idx0 < 64; idx0++ {
		for idx1 := 0; idx1 < 2; idx1++ {
			g_a[idx0][idx1] = t.G[idx0].A[idx1]
		}
	}
	var g_b [64]TestEnum
	for idx0 := 0; idx0 < 64; idx0++ {
		g_b[idx0] = t.G[idx0].B
	}
	var g_c [64][2]TestEnum
	for idx0 := 0; idx0 < 64; idx0++ {
		for idx1 := 0; idx1 < 2; idx1++ {
			g_c[idx0][idx1] = t.G[idx0].C[idx1]
		}
	}
	var g_d [64][2]int64
	for idx0 := 0; idx0 < 64; idx0++ {
		for idx1 := 0; idx1 < 2; idx1++ {
			g_d[idx0][idx1] = t.G[idx0].D[idx1]
		}
	}
	return CreateLargeArrayStruct(
		builder,
		t.D,
		t.E,
		t.F,
		g_a,
		g_b,
		g_c,
		g_d,
		t.H,
	)
}
func (rcv *LargeArrayStruct) UnPackTo(t *LargeArrayStructT) {
	for j := 0; j < 64; j++ {
		t.D[j] = rcv.D(j)
	}
	for j := 0; j < 64; j++ {
		t.E[j] = rcv.E(j)
	}
	for j := 0; j < 64; j++ {
		t.F[j] = rcv.F(j)
	}
	for j := 0; j < 64; j++ {
		x := NestedStruct{}
		t.G[j] = *rcv.G(&x, j).UnPack()
	}
	for j := 0; j < 64; j++ {
		t.H[j] = rcv.H(j)
	}
}

func (rcv *LargeArrayStruct) UnPack() *LargeArrayStructT {
	if rcv == nil {
		return nil
	}
	t := &LargeArrayStructT{}
	rcv.UnPackTo(t)
	return t
}

type LargeArrayStruct struct {
	_tab flatbuffers.Struct
}

func (rcv *LargeArrayStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LargeArrayStruct) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *LargeArrayStruct) D(j int) byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0) + flatbuffers.UOffsetT(j*1))
}

func (rcv *LargeArrayStruct) DLength() int {
	return 64
}

func (rcv *LargeArrayStruct) MutateD(j int, n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0)+flatbuffers.UOffsetT(j*1), n)
}

func (rcv *LargeArrayStruct) E(j int) float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(64) + flatbuffers.UOffsetT(j*4))
}

func (rcv *LargeArrayStruct) ELength() int {
	return 64
}

func (rcv *LargeArrayStruct) MutateE(j int, n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(64)+flatbuffers.UOffsetT(j*4), n)
}

func (rcv *LargeArrayStruct) F(j int) bool {
	return rcv._tab.GetBool(rcv._tab.Pos + flatbuffers.UOffsetT(320) + flatbuffers.UOffsetT(j*1))
}

func (rcv *LargeArrayStruct) FLength() int {
	return 64
}

func (rcv *LargeArrayStruct) MutateF(j int, n bool) bool {
	return rcv._tab.MutateBool(rcv._tab.Pos+flatbuffers.UOffsetT(320)+flatbuffers.UOffsetT(j*1), n)
}

func (rcv *LargeArrayStruct) G(obj *NestedStruct, j int) *NestedStruct {
	if obj == nil {
		obj = new(NestedStruct)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+flatbuffers.UOffsetT(384)+flatbuffers.UOffsetT(j*32))
	return obj
}

func (rcv *LargeArrayStruct) GLength() int {
	return 64
}

func (rcv *LargeArrayStruct) H(j int) TestEnum {
	return TestEnum(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(2432) + flatbuffers.UOffsetT(j*1)))
}

func (rcv *LargeArrayStruct) HLength() int {
	return 64
}

func (rcv *LargeArrayStruct) MutateH(j int, n TestEnum) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(2432)+flatbuffers.UOffsetT(j*1), int8(n))
}

func CreateLargeArrayStruct(builder *flatbuffers.Builder, d [64]byte, e [64]float32, f [64]bool, g_a [64][2]int32, g_b [64]TestEnum, g_c [64][2]TestEnum, g_d [64][2]int64, h [64]TestEnum) flatbuffers.UOffsetT {
	builder.Prep(8, 2496)
	for idx0 := 64 - 1; idx0 >= 0; idx0-- {
		builder.PrependInt8(int8(h[idx0]))
	}
	for idx0 := 64 - 1; idx0 >= 0; idx0-- {
		builder.Prep(8, 32)
		for idx1 := 2 - 1; idx1 >= 0; idx1-- {
			builder.PrependInt64(g_d[idx0][idx1])
		}
		builder.Pad(5)
		for idx1 := 2 - 1; idx1 >= 0; idx1-- {
			builder.PrependInt8(int8(g_c[idx0][idx1]))
		}
		builder.PrependInt8(int8(g_b[idx0]))
		for idx1 := 2 - 1; idx1 >= 0; idx1-- {
			builder.PrependInt32(g_a[idx0][idx1])
		}
	}
	for idx0 := 64 - 1; idx0 >= 0; idx0-- {
		builder.PrependBool(f[idx0])
	}
	for idx0 := 64 - 1; idx0 >= 0; idx0-- {
		builder.PrependFloat32(e[idx0])
	}
	for idx0 := 64 - 1; idx0 >= 0; idx0-- {
		builder.PrependByte(d[idx0])
	}
	return builder.Offset()
}
