// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Example

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NestedStructT struct {
	A [2]int32 `json:"a"`
	B TestEnum `json:"b"`
	C [2]TestEnum `json:"c"`
	D [2]int64 `json:"d"`
}

func (t *NestedStructT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateNestedStruct(builder, t.A, t.B, t.C, t.D)
}
func (rcv *NestedStruct) UnPackTo(t *NestedStructT) {
	for j := 0; j < 2; j++ {
		t.A[j] = rcv.A(j)
	}
	t.B = rcv.B()
	for j := 0; j < 2; j++ {
		t.C[j] = rcv.C(j)
	}
	for j := 0; j < 2; j++ {
		t.D[j] = rcv.D(j)
	}
}

func (rcv *NestedStruct) UnPack() *NestedStructT {
	if rcv == nil {
		return nil
	}
	t := &NestedStructT{}
	rcv.UnPackTo(t)
	return t
}

type NestedStruct struct {
	_tab flatbuffers.Struct
}

func (rcv *NestedStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NestedStruct) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *NestedStruct) A(j int) int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0) + flatbuffers.UOffsetT(j*4))
}

func (rcv *NestedStruct) ALength() int {
	return 2
}

func (rcv *NestedStruct) MutateA(j int, n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0)+flatbuffers.UOffsetT(j*4), n)
}

func (rcv *NestedStruct) B() TestEnum {
	return TestEnum(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(8)))
}
func (rcv *NestedStruct) MutateB(n TestEnum) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(8), int8(n))
}

func (rcv *NestedStruct) C(j int) TestEnum {
	return TestEnum(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(9) + flatbuffers.UOffsetT(j*1)))
}

func (rcv *NestedStruct) CLength() int {
	return 2
}

func (rcv *NestedStruct) MutateC(j int, n TestEnum) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(9)+flatbuffers.UOffsetT(j*1), int8(n))
}

func (rcv *NestedStruct) D(j int) int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(16) + flatbuffers.UOffsetT(j*8))
}

func (rcv *NestedStruct) DLength() int {
	return 2
}

func (rcv *NestedStruct) MutateD(j int, n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(16)+flatbuffers.UOffsetT(j*8), n)
}

func CreateNestedStruct(builder *flatbuffers.Builder, a [2]int32, b TestEnum, c [2]TestEnum, d [2]int64) flatbuffers.UOffsetT {
	builder.Prep(8, 32)
	for idx0 := 2 - 1; idx0 >= 0; idx0-- {
		builder.PrependInt64(d[idx0])
	}
	builder.Pad(5)
	for idx0 := 2 - 1; idx0 >= 0; idx0-- {
		builder.PrependInt8(int8(c[idx0]))
	}
	builder.PrependInt8(int8(b))
	for idx0 := 2 - 1; idx0 >= 0; idx0-- {
		builder.PrependInt32(a[idx0])
	}
	return builder.Offset()
}
